### ISSUE TITLE
Xp is not obtained when simple harvest

### ISSUE THREAD

**Issue by Luicuelo** [Real-Gecko/XPFromHarvest#5]
Not giving xp when "Simple Harvest" = true
Version: XPFromHarvest-1.15.2-1.2.0.jar

**Comment by Real-Gecko** [comment]
More details please, maybe log file?

**Comment by Luicuelo** [comment]
To reproduce the problem, activate the "simple harvest" option in the config and when the crops are right-clicked, no experience will be gained.
Nothing appears in the log as there is no crash or something similar

**Comment by Real-Gecko** [comment]
What other mods do you have? Currently many mods implement simple harvest functionality (even Quark has one), this may clash with XPFH simple harvest functionality.

**Comment by Luicuelo** [comment]
I think there is no conflict,  if I remove XPFromHarvest right click no longer works.

I attach the rest of the mods, but none add functionalities related to crops


268566;MekanismGenerators-;
268567;MekanismTools-;
345425;MekanismAdditions-;
268560;Mekanism-;
353051;GameMenuModOption-;
240633;inventorysorter-;
248787;AppleSkin-mc;
352835;backpacked-;
228525;Bookshelf-;
243883;ChickenChunks-;
242818;CodeChickenLib-;
276951;comforts-FORGE;
239197;CraftTweaker-;
328085;create-mc;2
267602;CTM-MC;2
309927;curios-FORGE;
232758;CyclopsCore-;
291936;findme-;
290404;Flopper-;
238551;gravestone-;
253449;Hwyla-forge;
231951;ImmersiveEngineering-;
228756;ironchest-;
238222;jei-;
32274;journeymap-;
240630;JustEnoughResources-;
351948;mining-helmet;
252848;NaturesCompass-;
238372;Neat;
296686;rsgauges-;
223852;StorageDrawers-;
79287;WailaHarvestability-mc;
224712;WAWLA-;
289397;XPFromHarvest-;

**Comment by Real-Gecko** [comment]
Modpack?

**Comment by Luicuelo** [comment]
Curseforge modpack, LightTechImm id:407268

**Comment by Real-Gecko** [comment]
Cannot find that one, can you provide link?

**Comment by Luicuelo** [comment]
https://www.curseforge.com/minecraft/modpacks/lighttechimm

**Comment by Real-Gecko** [comment]
I tried your modpack and everything looks good, right clicking on mature crop harvests it and gives xp. Can you post your config? Default should be:
```toml
#Enable simple harvesting and replanting with right click
"Simple Harvest" = true
#Curiosity Mode: sneak + right click with on block to get info in chat
Curiosity = false
#List of crops to process with their ages
"Crops List" = ["Block{minecraft:potatoes}[age=7]", "Block{minecraft:carrots}[age=7]", "Block{minecraft:wheat}[age=7]", "Block{minecraft:beetroots}[age=3]", "Block{minecraft:nether_wart}[age=3]"]
#Amount of XP given
#Range: > 1
"XP Amount" = 1
#Chance in % of XP orb spawning after harvest done
#Range: 1 ~ 100
Chance = 100
```
